config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  # root 'static#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :landings
  # get '/auth/:provider/callback', to: 'sessions#create'

  resources :channels
  resources :messages
  resources :pins

  devise_scope :user do
    get '/signout', to: 'devise/sessions#destroy', as: :signout
  end


  post "/pins" => "pins#create"
  # get ':action' => 'static#:action'
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  belongs_to :user
  has_many :messages

  def self.current_channels(current_user)
    count = 1
    raw_channels = get_channels_from_slack(current_user.token)
    current_channel = raw_channels.map do |channel|
      channel_id = channel["id"]
      channel_name = channel["name"]
      purpose = channel["purpose"]["value"]
      id = count
      count = count + 1
      new(id: id, channel_id: channel_id, channel_name: channel_name, purpose: purpose)
    end
  end

  def self.get_channels_from_slack(token)
    uri = URI("https://slack.com/api/channels.list?token=#{token}&pretty=1")
    response = Net::HTTP.get_response(uri)
    channels = JSON.parse(response.body)["channels"]
  end

  private

  def channel_params
    params.require(:message).permit(:channel_id, :channel_name, :purpose)
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
before_action :authenticate_user!
  def index
    if !(current_user.nil?)
      Channel.delete_all
      Channel.reset_pk_sequence
      get_team_info
      create
    end
  end

  def create
    @channels = Channel.current_channels(current_user)
    @channels.each do |channel|
      Channel.create(channel_id: channel.channel_id,
      channel_name: channel.channel_name, purpose: channel.purpose)
    end
  end

  def show
    get_team_info
    @channel = Channel.find(params[:id])
    Message.delete_all
    Message.reset_pk_sequence
    @messages = Message.current_messages(current_user, @channel)
    @messages.each do |message|
      Message.create(slack_username: message.slack_username,
      ts: message.ts, slack_message: message.slack_message,
      user_id: current_user.id)
    end
  end

private

def channel_params
  params.require(:channel).permit(
    :id,
    :channel_id,
    :channel_name,
    :purpose
  )
end

end

app/views/channels/index.html.erb
<body>
<div class="row">
  <div class="test-move">
    <div class="large-12 columns test-box" style="background-color:white;">
      <center><h2 class="channel-title"><%= @team_name %></h2><br>
      <h3 class="roboto-stuff">Current Channels</h3></center><br>
      <% if !current_user.nil? %>
        <ul>
          <% @channels.each do |channel| %>
            <li><b><%= link_to "##{channel.channel_name}", channel_path(channel.id) %>:
            </b> <%= "#{channel.purpose}" %></li>
          <% end %>
      </ul>
      <% end %>
    </div>

</div>
</body>

app/views/channels/show.html.erb
<div class="row">

  <div class="large-12 columns test-box test-move" style="background-color:white;">
    <center><h2 class="channel-title">#<%= @channel.channel_name%></h2><b><h2 class="roboto-stuff"> - Recent Messages</h2>
    </center></b><br>
    <% if !current_user.nil? %>

      <ul>
      <% @messages.each do |message| %>
      <% x = message.slack_message %>
      <% x = x.tr('<>', '') %>
      <% y = auto_link(x, html: { target: '_blank' }) %>

      <li><b><%="#{message.slack_username}"%></b>
        <%= "(#{message.ts.strftime('%m/%d/%Y %I:%M%p')}): "%><%= y %> <b>•

          <%= link_to "Save", new_pin_path(message), method: :get %>
         </b>
      </li>
      <% end %><br>
      <b><center><b><h4><%= link_to "Return to Slack Channels", channels_path %></b></h4></center><br>
    </ul>
    <% end %>
  </div>

</div>
</body>