config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  # root 'static#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :landings
  # get '/auth/:provider/callback', to: 'sessions#create'

  resources :channels
  resources :messages
  resources :pins

  devise_scope :user do
    get '/signout', to: 'devise/sessions#destroy', as: :signout
  end


  post "/pins" => "pins#create"
  # get ':action' => 'static#:action'
end

app/views/layouts/_header.html.erb
<nav class="bar-no-margin" data-topbar role="navigation">

    <p class="name">
      <%= link_to image_tag("slacktracklogo.png"), landings_path %>

    </p>
  <ul class="title-area">
    <li class="toggle-topbar">
      <% if user_signed_in? %>
        <% if !(current_user.name == nil) %>
          <li> Signed in as  <p class="fancy"><%= current_user.name %></p><br>Team <b><%= @team_name %></b></li>
          <li><b><%= link_to 'Channels', channels_path %> ||
          <%= link_to 'Pinned Messages', pins_path %></li></b>
        <% else %>
          <li> Signed in on Team <b><%= @team_name %></b> </li>
          <li><b><%= link_to 'Channels', channels_path %> ||
          <%= link_to 'Pinned Messages', pins_path %></li></b>
        <% end %>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %> <b>||</b> <%= link_to "Sign Into Another Team", '/users/auth/slack' %></li>
      <% else %>
        <li><%= link_to 'Sign In', '/users/auth/slack' %></li>

      <% end %>
    </li>

  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "SlackTrack" %></title>
      <link href='//fonts.googleapis.com/css?family=Leckerli One' rel='stylesheet' type='text/css'>
      <link href='//fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= google_webfonts_init({
      google: ['Roboto Condensed']
    }) %>
    <%= google_webfonts_init({
      google: ['Roboto']
    }) %>
    <%= google_webfonts_init({
      google: ['Leckerli One']
    }) %>
    <script type="text/javascript" script-name="annie-use-your-telescope" src="http://use.edgefonts.net/annie-use-your-telescope.js"></script>
  </head>

  <body>

    <%= render 'layouts/header' %>
    <%= yield %>

  </body>
</html>